if(NOT DEFINED LYRA_EXE OR NOT DEFINED SOURCE_FILE OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "LYRA_EXE, SOURCE_FILE and OUTPUT_DIR are required")
endif()
set(FLOAT_WAV "${OUTPUT_DIR}/float32-192k-test.wav")
execute_process(COMMAND "${LYRA_EXE}" -r 192000 -b 32 "${SOURCE_FILE}" "${FLOAT_WAV}"
    RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_VARIABLE ERROR_TEXT)
if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "32-float/192k render failed: ${ERROR_TEXT}")
endif()
file(READ "${FLOAT_WAV}" FORMAT_HEX OFFSET 20 LIMIT 2 HEX)
file(READ "${FLOAT_WAV}" RATE_HEX OFFSET 24 LIMIT 4 HEX)
file(READ "${FLOAT_WAV}" BITS_HEX OFFSET 34 LIMIT 2 HEX)
if(NOT FORMAT_HEX STREQUAL "0300" OR NOT RATE_HEX STREQUAL "00ee0200" OR NOT BITS_HEX STREQUAL "2000")
    message(FATAL_ERROR "WAV is not IEEE-float 192kHz/32-bit: ${FORMAT_HEX} ${RATE_HEX} ${BITS_HEX}")
endif()

set(STEMS_DIR "${OUTPUT_DIR}/verified-stems")
set(ANALYSIS_FILE "${OUTPUT_DIR}/verified-analysis.json")
set(MASTER_FILE "${OUTPUT_DIR}/verified-master.wav")
file(REMOVE_RECURSE "${STEMS_DIR}")
execute_process(COMMAND "${LYRA_EXE}" --stems "${STEMS_DIR}" --analysis "${ANALYSIS_FILE}"
    "${SOURCE_FILE}" "${MASTER_FILE}" RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_VARIABLE ERROR_TEXT)
if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "Stem/analysis render failed: ${ERROR_TEXT}")
endif()
file(GLOB STEMS "${STEMS_DIR}/*.wav")
list(LENGTH STEMS STEM_COUNT)
if(NOT STEM_COUNT EQUAL 3)
    message(FATAL_ERROR "Expected 3 stems, got ${STEM_COUNT}")
endif()
list(GET STEMS 0 STEM_A)
list(GET STEMS 1 STEM_B)
file(SHA256 "${STEM_A}" HASH_A)
file(SHA256 "${STEM_B}" HASH_B)
if(HASH_A STREQUAL HASH_B)
    message(FATAL_ERROR "Different tracks produced identical stems")
endif()
file(READ "${ANALYSIS_FILE}" ANALYSIS_TEXT)
foreach(EXPECTED "\"peak_dbfs\"" "\"integrated_lufs\"" "\"stereo_correlation\""
                 "\"clipped_samples\"" "\"spectrum_db\"" "\"waveform_peaks\"")
    string(FIND "${ANALYSIS_TEXT}" "${EXPECTED}" POSITION)
    if(POSITION EQUAL -1)
        message(FATAL_ERROR "Analysis JSON is missing ${EXPECTED}")
    endif()
endforeach()

set(COMMAND_ANALYSIS "${OUTPUT_DIR}/verified-analyze-command.json")
execute_process(COMMAND "${LYRA_EXE}" analyze "${SOURCE_FILE}" "${COMMAND_ANALYSIS}"
    RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_VARIABLE ERROR_TEXT)
if(NOT RESULT EQUAL 0 OR NOT EXISTS "${COMMAND_ANALYSIS}")
    message(FATAL_ERROR "Analyze command failed: ${ERROR_TEXT}")
endif()
